### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by HareIam** [photom/pyaudacity_noisered#1]
Hi,

I meet following error, when I run: `python setup.py install`:

`(myenv) xsh@xsh-VirtualBox:~/Downloads/pyaudacity_noisered-master$ python setup.py install
running install
running build
running build_py
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/pyaudacity
copying src/pyaudacity/__init__.py -> build/lib.linux-x86_64-3.6/pyaudacity
running build_ext
building 'cmodule' extension
creating build/temp.linux-x86_64-3.6
creating build/temp.linux-x86_64-3.6/src
creating build/temp.linux-x86_64-3.6/src/audacity
creating build/temp.linux-x86_64-3.6/src/pyaudacity
gcc -pthread -B /home/xsh/anaconda3/envs/myenv/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Isrc/audacity -I/home/xsh/anaconda3/envs/myenv/include/python3.6m -c src/audacity/ExportPCM.cpp -o build/temp.linux-x86_64-3.6/src/audacity/ExportPCM.o -std=c++14 -Wextra -pedantic -Wno-unused-parameter -Wno-unused-variable -Wno-implicit-fallthrough
gcc -pthread -B /home/xsh/anaconda3/envs/myenv/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Isrc/audacity -I/home/xsh/anaconda3/envs/myenv/include/python3.6m -c src/audacity/SampleFormat.cpp -o build/temp.linux-x86_64-3.6/src/audacity/SampleFormat.o -std=c++14 -Wextra -pedantic -Wno-unused-parameter -Wno-unused-variable -Wno-implicit-fallthrough
gcc -pthread -B /home/xsh/anaconda3/envs/myenv/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Isrc/audacity -I/home/xsh/anaconda3/envs/myenv/include/python3.6m -c src/audacity/Export.cpp -o build/temp.linux-x86_64-3.6/src/audacity/Export.o -std=c++14 -Wextra -pedantic -Wno-unused-parameter -Wno-unused-variable -Wno-implicit-fallthrough
gcc -pthread -B /home/xsh/anaconda3/envs/myenv/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Isrc/audacity -I/home/xsh/anaconda3/envs/myenv/include/python3.6m -c src/audacity/NoiseReduction.cpp -o build/temp.linux-x86_64-3.6/src/audacity/NoiseReduction.o -std=c++14 -Wextra -pedantic -Wno-unused-parameter -Wno-unused-variable -Wno-implicit-fallthrough
gcc -pthread -B /home/xsh/anaconda3/envs/myenv/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Isrc/audacity -I/home/xsh/anaconda3/envs/myenv/include/python3.6m -c src/audacity/FileFormats.cpp -o build/temp.linux-x86_64-3.6/src/audacity/FileFormats.o -std=c++14 -Wextra -pedantic -Wno-unused-parameter -Wno-unused-variable -Wno-implicit-fallthrough
gcc -pthread -B /home/xsh/anaconda3/envs/myenv/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Isrc/audacity -I/home/xsh/anaconda3/envs/myenv/include/python3.6m -c src/audacity/wxFileName.cpp -o build/temp.linux-x86_64-3.6/src/audacity/wxFileName.o -std=c++14 -Wextra -pedantic -Wno-unused-parameter -Wno-unused-variable -Wno-implicit-fallthrough
gcc -pthread -B /home/xsh/anaconda3/envs/myenv/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Isrc/audacity -I/home/xsh/anaconda3/envs/myenv/include/python3.6m -c src/audacity/DirManager.cpp -o build/temp.linux-x86_64-3.6/src/audacity/DirManager.o -std=c++14 -Wextra -pedantic -Wno-unused-parameter -Wno-unused-variable -Wno-implicit-fallthrough
src/audacity/DirManager.cpp:70:19: fatal error: zconf.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1
`

Can anyone help on it?

Thanks!
Shihao

**Comment by photom** [comment]
```
fatal error: zconf.h: No such file or directory
```
Error log seems to say zlib library is missing.
How about installing zlib library.
For Redhat(centos, fedra) users: zlib-devel
For Debian(ubuntu) users: zlib1g-dev

**Comment by HareIam** [comment]
Thanks for your feedback! I think I have successfully installed the packages and pyaudacity.

Now I am testing the code using test_noisered.py:

`
import unittest
import pyaudacity
import numpy as np
from scipy.io import wavfile
from scipy.signal import spectrogram
# import yep


# Calculate spectrogram for a wav audio file
def create_spectrogram(wav_file):
    rate, data = wavfile.read(wav_file)
    nfft = 200  # Length of each window segment
    fs = 8000  # Sampling frequencies
    noverlap = 120  # Overlap between windows
    nchannels = data.ndim
    if nchannels == 1:
        freqs, bins, pxx = spectrogram(data, fs, nperseg=nfft, noverlap=noverlap)
    elif nchannels == 2:
        freqs, bins, pxx = spectrogram(data[:, 0], fs, nperseg=nfft, noverlap=noverlap)
    else:
        raise RuntimeError("invalid channels. file={wav_file}")
    return pxx


class TestSpectrogram(unittest.TestCase):
    def test_noisered(self):
        input = '/var/tmp/keyword_recognizer/input.wav'
        prof = '/var/tmp/keyword_recognizer/bg_input.wav'
        output = '/var/tmp/keyword_recognizer/noisered.wav'

        # yep.start('outcome.prof')
        result = pyaudacity.noisered('../test.wav', 0.000, 0.300, '../test.wav', 12.0, 6.0, 3.0, 'test_out.wav')
        #result = pyaudacity.noisered(prof, 0.000, 0.500, input, 12.0, 6.0, 3.0, output)
        #self.assertEqual(result, True)
        # expected = create_spectrogram('../test_answer.wav')
        # actual = create_spectrogram('test_out.wav')
        # result does not match
        # np.testing.assert_almost_equal(expected, actual, decimal=5)
        # yep.stop()


if __name__ == '__main__':
    unittest.main()
`

where I am only running `result = pyaudacity.noisered('../test.wav', 0.000, 0.300, '../test.wav', 12.0, 6.0, 3.0, 'test_out.wav')`

However, no output audio generated and with error:

`Segmentation fault (core dumped)`

Any idea about this issue. I have no clue.

Thanks!

Xu Shihao

**Comment by Xu-Shihao** [comment]
It works well now. Good job.

Thanks.
Shihao
